scoreboard_user:
    resource: "@ScoreboardUserBundle/Controller/"
    type:     annotation
    prefix:   /

scoreboard_app:
    resource: "@ScoreboardAppBundle/Controller/"
    type:     annotation
    prefix:   /

_fos:
    resource: routing_fos.yml